#!/bin/sh

D_PPC_=1
D_PIX_DEPTH_=8
D_TOP_=$(cat ../TOP)_Ppc${D_PPC_}_Dep${D_PIX_DEPTH_}

CFLAGS="-DD_TOP_=$D_TOP_ -DD_ENABLE_PIXEL_CNTR_ -DD_ENABLE_LINE_CNTR_ -DD_ENABLE_FRAME_CNTR_ -DD_PIX_DEPTH_=$D_PIX_DEPTH_ -DD_PPC_=$D_PPC_"
