#!/bin/sh

D_MAX_MTU_=1500
D_MIN_MTU_=46
D_RETURN_S_AXILITE_=1
D_RETURN_AP_CTRL_HS_=0;
D_TOP_=$(cat ../TOP)

CFLAGS=""
CFLAGS="$CFLAGS -DD_MAX_MTU_=$D_MAX_MTU_"
CFLAGS="$CFLAGS -DD_MIN_MTU_=$D_MIN_MTU_"
CFLAGS="$CFLAGS -DD_RETURN_S_AXILITE_=$D_RETURN_S_AXILITE_"
CFLAGS="$CFLAGS -DD_RETURN_AP_CTRL_HS_=$D_RETURN_AP_CTRL_HS_"
CFLAGS="$CFLAGS -DD_TOP_=$D_TOP_"
