#!/bin/sh

CFLAGS="-DD_ROW_=1080 -DD_COL_=1920 -DD_FIELD_BLANK_=200 -DD_LINE_BLANK_=100 -DD_PPC_=1 -DD_VID_DWIDTH_=16 -DD_AXIS_DWIDTH_=24 -DD_OVERRIDE_COL_ROW_" COSIMFLAGS="-DD_VERBOSE_ -DD_N_FRAMES_=3" vitis_hls -f cosim.tcl
