#!/bin/sh

CFLAGS="-DD_MAX_MTU_=1500 -DD_OCTET_BW_=8 -DD_SRC_ADDR_MSB_N_OCTETS_=2 -DD_SRC_ADDR_LSB_N_OCTETS_=4 -DD_DEST_ADDR_MSB_N_OCTETS_=2 -DD_DEST_ADDR_LSB_N_OCTETS_=4 -DD_ETHER_TYPE_N_OCTETS_=2 -DD_PREAMBLE_N_OCTETS_=7 -DD_SFD_N_OCTETS_=1 -DD_MSB_FIRST_=1 -DD_CRC32_N_OCTETS_=4" vitis_hls -f cosim.tcl
