#if !defined(HLS_ETH_MAC_PARAMS_H_INCLUDE_GUARD_)
#define HLS_ETH_MAC_PARAMS_H_INCLUDE_GUARD_

static const auto OCTET_BW_=D_OCTET_BW_;
static const auto PREAMBLE_N_OCTETS_=D_PREAMBLE_N_OCTETS_;
static const auto SFD_N_OCTETS_=D_SFD_N_OCTETS_;
static const auto DEST_ADDR_MSB_N_OCTETS_=D_DEST_ADDR_MSB_N_OCTETS_;
static const auto DEST_ADDR_LSB_N_OCTETS_=D_DEST_ADDR_LSB_N_OCTETS_;
static const auto SRC_ADDR_MSB_N_OCTETS_=D_SRC_ADDR_MSB_N_OCTETS_;
static const auto SRC_ADDR_LSB_N_OCTETS_=D_SRC_ADDR_LSB_N_OCTETS_;
static const auto ETHER_TYPE_N_OCTETS_=D_ETHER_TYPE_N_OCTETS_; 
static const auto MAX_MTU_=D_MAX_MTU_;
static const auto CRC32_N_OCTETS_=D_CRC32_N_OCTETS_;

#define AP_CTRL_NONE_ D_AP_CTRL_NONE_
#define S_AXILITE_ D_S_AXILITE_
#define LSB_FIRST_ D_LSB_FIRST_
#define MSB_FIRST_ D_MSB_FIRST_
#define HLS_CSIM_ D_HLS_CSIM_

#endif
